package ee.forgr.capacitor_updater;

import android.content.SharedPreferences;
import android.util.Log;

import com.android.volley.AuthFailureError;
import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.StringRequest;
import com.getcapacitor.plugin.WebView;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FilenameFilter;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLConnection;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

interface Callback {
    void callback(JSONObject jsonObject);
}

public class CapacitorUpdater {
    private static final String AB = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    private static final SecureRandom rnd = new SecureRandom();

    private static final String INFO_SUFFIX = "_info";

    private static final String FALLBACK_VERSION = "pastVersion";
    private static final String NEXT_VERSION = "nextVersion";
    private static final String bundleDirectory = "versions";

    public static final String TAG = "Capacitor-updater";
    public static final String pluginVersion = "4.0.0";

    public SharedPreferences.Editor editor;
    public SharedPreferences prefs;

    public RequestQueue requestQueue;

    public File documentsDir;
    public String versionBuild = "";
    public String versionCode = "";
    public String versionOs = "";

    public String statsUrl = "";
    public String appId = "";
    public String deviceID = "";

    private final FilenameFilter filter = new FilenameFilter() {
        @Override
        public boolean accept(final File f, final String name) {
            // ignore directories generated by mac os x
            return !name.startsWith("__MACOSX") && !name.startsWith(".") && !name.startsWith(".DS_Store");
        }
    };

    private int calcTotalPercent(final int percent, final int min, final int max) {
        return (percent * (max - min)) / 100 + min;
    }

    void notifyDownload(final String id, final int percent) {
        return;
    }

    private String randomString(final int len){
        final StringBuilder sb = new StringBuilder(len);
        for(int i = 0; i < len; i++)
            sb.append(AB.charAt(rnd.nextInt(AB.length())));
        return sb.toString();
    }

    private File unzip(final String id, final File zipFile, final String dest) throws IOException {
        final File targetDirectory = new File(this.documentsDir, dest);
        final ZipInputStream zis = new ZipInputStream(new BufferedInputStream(new FileInputStream(zipFile)));
        try {
            int count;
            final int bufferSize = 8192;
            final byte[] buffer = new byte[bufferSize];
            final long lengthTotal = zipFile.length();
            long lengthRead = bufferSize;
            int percent = 0;
            this.notifyDownload(id, 75);

            ZipEntry entry;
            while ((entry = zis.getNextEntry()) != null) {
                final File file = new File(targetDirectory, entry.getName());
                final String canonicalPath = file.getCanonicalPath();
                final String canonicalDir = (new File(String.valueOf(targetDirectory))).getCanonicalPath();
                final File dir = entry.isDirectory() ? file : file.getParentFile();

                if (!canonicalPath.startsWith(canonicalDir)) {
                    throw new FileNotFoundException("SecurityException, Failed to ensure directory is the start path : " +
                            canonicalDir + " of " + canonicalPath);
                }

                if (!dir.isDirectory() && !dir.mkdirs()) {
                    throw new FileNotFoundException("Failed to ensure directory: " +
                            dir.getAbsolutePath());
                }

                if (entry.isDirectory()) {
                    continue;
                }

                try(final FileOutputStream outputStream = new FileOutputStream(file)) {
                    while ((count = zis.read(buffer)) != -1)
                        outputStream.write(buffer, 0, count);
                }

                final int newPercent = (int)((lengthRead * 100) / lengthTotal);
                if (lengthTotal > 1 && newPercent != percent) {
                    percent = newPercent;
                    this.notifyDownload(id, this.calcTotalPercent(percent, 75, 90));
                }

                lengthRead += entry.getCompressedSize();
            }
            return targetDirectory;
        } finally {
            try {
                zis.close();
            } catch (final IOException e) {
                Log.e(TAG, "Failed to close zip input stream", e);
            }
        }
    }

    private void flattenAssets(final File sourceFile, final String dest) throws IOException {
        if (!sourceFile.exists()) {
            throw new FileNotFoundException("Source file not found: " + sourceFile.getPath());
        }
        final File destinationFile = new File(this.documentsDir, dest);
        destinationFile.getParentFile().mkdirs();
        final String[] entries = sourceFile.list(this.filter);
        if (entries == null || entries.length == 0) {
            throw new IOException("Source file was not a directory or was empty: " + sourceFile.getPath());
        }
        if (entries.length == 1 && !"index.html".equals(entries[0])) {
            final File child = new File(sourceFile, entries[0]);
            child.renameTo(destinationFile);
        } else {
            sourceFile.renameTo(destinationFile);
        }
        sourceFile.delete();
    }

    private File downloadFile(final String id, final String url, final String dest) throws IOException {

        final URL u = new URL(url);
        final URLConnection connection = u.openConnection();
        final InputStream is = u.openStream();
        final DataInputStream dis = new DataInputStream(is);

        final File target = new File(this.documentsDir, dest);
        target.getParentFile().mkdirs();
        target.createNewFile();
        final FileOutputStream fos = new FileOutputStream(target);

        final long totalLength = connection.getContentLength();
        final int bufferSize = 1024;
        final byte[] buffer = new byte[bufferSize];
        int length;

        int bytesRead = bufferSize;
        int percent = 0;
        this.notifyDownload(id, 10);
        while ((length = dis.read(buffer))>0) {
            fos.write(buffer, 0, length);
            final int newPercent = (int)((bytesRead * 100) / totalLength);
            if (totalLength > 1 && newPercent != percent) {
                percent = newPercent;
                this.notifyDownload(id, this.calcTotalPercent(percent, 10, 70));
            }
            bytesRead += length;
        }
        return target;
    }

    private void deleteDirectory(final File file) throws IOException {
        if (file.isDirectory()) {
            final File[] entries = file.listFiles();
            if (entries != null) {
                for (final File entry : entries) {
                    this.deleteDirectory(entry);
                }
            }
        }
        if (!file.delete()) {
            throw new IOException("Failed to delete: " + file);
        }
    }

    private void setCurrentBundle(final File bundle) {
        this.editor.putString(WebView.CAP_SERVER_PATH, bundle.getPath());
        Log.i(TAG, "Current bundle set to: " + bundle);
        this.editor.commit();
    }

    public BundleInfo download(final String url, final String version) throws IOException {
        final String id = this.randomString(10);
        this.saveBundleInfo(id, new BundleInfo(id, version, BundleStatus.DOWNLOADING, new Date(System.currentTimeMillis())));
        this.notifyDownload(id, 0);
        final String idName = bundleDirectory + "/" + id;
        this.notifyDownload(id, 5);
        final File downloaded = this.downloadFile(id, url, this.randomString(10));
        this.notifyDownload(id, 71);
        final File unzipped = this.unzip(id, downloaded, this.randomString(10));
        downloaded.delete();
        this.notifyDownload(id, 91);
        this.flattenAssets(unzipped, idName);
        this.notifyDownload(id, 100);
        this.saveBundleInfo(id, null);
        BundleInfo info = new BundleInfo(id, version, BundleStatus.PENDING, new Date(System.currentTimeMillis()));
        this.saveBundleInfo(id, info);
        return info;
    }

    public List<BundleInfo> list() {
        final List<BundleInfo> res = new ArrayList<>();
        final File destHot = new File(this.documentsDir, bundleDirectory);
        Log.d(TAG, "list File : " + destHot.getPath());
        if (destHot.exists()) {
            for (final File i : destHot.listFiles()) {
                final String id = i.getName();
                res.add(this.getBundleInfo(id));
            }
        } else {
            Log.i(TAG, "No versions available to list" + destHot);
        }
        return res;
    }

    public Boolean delete(final String id) throws IOException {
        final BundleInfo deleted = this.getBundleInfo(id);
        final File bundle = new File(this.documentsDir, bundleDirectory + "/" + id);
        if (bundle.exists()) {
            this.deleteDirectory(bundle);
            this.removeBundleInfo(id);
            return true;
        }
        Log.e(TAG, "Directory not removed: " + bundle.getPath());
        this.sendStats("delete", deleted);
        return false;
    }

    private File getBundleDirectory(final String id) {
        return new File(this.documentsDir, bundleDirectory + "/" + id);
    }

    private boolean bundleExists(final File bundle) {
        if(bundle == null || !bundle.exists()) {
            return false;
        }

        return new File(bundle.getPath(), "/index.html").exists();
    }

    public Boolean set(final BundleInfo bundle) {
        return this.set(bundle.getId());
    }

    public Boolean set(final String id) {

        final BundleInfo existing = this.getBundleInfo(id);
        final File bundle = this.getBundleDirectory(id);

        Log.i(TAG, "Setting next active bundle: " + existing);
        if (this.bundleExists(bundle)) {
            this.setCurrentBundle(bundle);
            this.setBundleStatus(id, BundleStatus.PENDING);
            this.sendStats("set", existing);
            return true;
        }
        this.sendStats("set_fail", existing);
        return false;
    }

    public void commit(final BundleInfo bundle) {
        this.setBundleStatus(bundle.getVersionName(), BundleStatus.SUCCESS);
        this.setFallbackVersion(bundle);
    }

    public void reset() {
        this.reset(false);
    }

    public void rollback(final BundleInfo bundle) {
        this.setBundleStatus(bundle.getVersionName(), BundleStatus.ERROR);
    }

    public void reset(final boolean internal) {
        this.setCurrentBundle(new File("public"));
        this.setFallbackVersion(null);
        this.setNextVersion(null);
        if(!internal) {
            this.sendStats("reset", this.getCurrentBundle());
        }
    }

    public void getLatest(final String url, final Callback callback) {
        final String deviceID = this.deviceID;
        final String appId = this.appId;
        final String versionBuild = this.versionBuild;
        final String versionCode = this.versionCode;
        final String versionOs = this.versionOs;
        final String pluginVersion = CapacitorUpdater.pluginVersion;
        final String version = this.getCurrentBundle().getId();
        final StringRequest stringRequest = new StringRequest(Request.Method.GET, url,
                new Response.Listener<String>() {
                    @Override
                    public void onResponse(final String response) {
                        try {
                            final JSONObject jsonObject = new JSONObject(response);
                            callback.callback(jsonObject);
                        } catch (final JSONException e) {
                            Log.e(TAG, "Error parsing JSON", e);
                        }
                    }
                }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(final VolleyError error) {
                Log.e(TAG, "Error getting Latest" +  error);
            }
        }) {
            @Override
            public Map<String, String> getHeaders() throws AuthFailureError {
                final Map<String, String>  params = new HashMap<String, String>();
                params.put("cap_platform", "android");
                params.put("cap_device_id", deviceID);
                params.put("cap_app_id", appId);
                params.put("cap_version_build", versionBuild);
                params.put("cap_version_code", versionCode);
                params.put("cap_version_os", versionOs);
                params.put("cap_version_name", version);
                params.put("cap_plugin_version", pluginVersion);
                return params;
            }
        };
        this.requestQueue.add(stringRequest);
    }

    public void sendStats(final String action, final BundleInfo bundle) {
        String statsUrl = this.statsUrl;
        if (statsUrl == null || "".equals(statsUrl) || statsUrl.length() == 0) { return; }
        final URL url;
        final JSONObject json = new JSONObject();
        final String jsonString;
        try {
            url = new URL(statsUrl);
            json.put("platform", "android");
            json.put("action", action);
            json.put("version_name", bundle.getVersionName());
            json.put("device_id", this.deviceID);
            json.put("version_build", this.versionBuild);
            json.put("version_code", this.versionCode);
            json.put("version_os", this.versionOs);
            json.put("plugin_version", pluginVersion);
            json.put("app_id", this.appId);
            jsonString = json.toString();
        } catch (final Exception ex) {
            Log.e(TAG, "Error get stats", ex);
            return;
        }
        new Thread(new Runnable(){
            @Override
            public void run() {
                HttpURLConnection con = null;
                try {
                    con = (HttpURLConnection) url.openConnection();
                    con.setRequestMethod("POST");
                    con.setRequestProperty("Content-Type", "application/json");
                    con.setRequestProperty("Accept", "application/json");
                    con.setRequestProperty("Content-Length", Integer.toString(jsonString.getBytes().length));
                    con.setDoOutput(true);
                    con.setConnectTimeout(500);
                    final DataOutputStream wr = new DataOutputStream (con.getOutputStream());
                    wr.writeBytes(jsonString);
                    wr.close();
                    final int responseCode = con.getResponseCode();
                    if (responseCode != 200) {
                        Log.e(TAG, "Stats error responseCode: " + responseCode);
                    } else {
                        Log.i(TAG, "Stats send for \"" + action + "\", version " + bundle.getVersionName());
                    }
                } catch (final Exception ex) {
                    Log.e(TAG, "Error post stats", ex);
                } finally {
                    if (con != null) {
                        con.disconnect();
                    }
                }
            }
        }).start();
    }

    public BundleInfo getBundleInfo(String id) {
        if(id == null) {
            id = BundleInfo.VERSION_UNKNOWN;
        }
        Log.d(TAG, "Getting info for [" + id + "]");
        BundleInfo result;
        if(BundleInfo.VERSION_BUILTIN.equals(id)) {
            result = new BundleInfo(id, (String) null, BundleStatus.SUCCESS, "");
        } else {
            try {
                String stored = this.prefs.getString(id + INFO_SUFFIX, "");
                result = BundleInfo.fromJSON(stored);
            } catch (JSONException e) {
                Log.e(TAG, "Failed to parse id info for [" + id + "] ", e);
                result = new BundleInfo(id, (String) null, BundleStatus.PENDING, "");
            }
        }

        Log.d(TAG, "Returning info [" + id + "] " + result);
        return result;
    }

    public BundleInfo getBundleInfoByName(final String id) {
        final List<BundleInfo> installed = this.list();
        for(final BundleInfo i : installed) {
            if(i.getId().equals(id)) {
                return i;
            }
        }
        return null;
    }

    private void removeBundleInfo(final String id) {
        this.saveBundleInfo(id, null);
    }

    private void saveBundleInfo(final String id, final BundleInfo info) {
        if(id == null || (info != null && (info.isBuiltin() || info.isUnknown()))) {
            Log.d(TAG, "Not saving info for id: [" + id + "] " + info);
            return;
        }

        if(info == null) {
            Log.d(TAG, "Removing info for id [" + id + "]");
            this.editor.remove(id + INFO_SUFFIX);
        } else {
            final BundleInfo update = info.setId(id);
            Log.d(TAG, "Storing info for id [" + id + "] " + update.toString());
            this.editor.putString(id + INFO_SUFFIX, update.toString());
        }
        this.editor.commit();
    }

    public void setVersionName(final String id, final String name) {
        if(id != null) {
            Log.d(TAG, "Setting name for id [" + id + "] to " + name);
            BundleInfo info = this.getBundleInfo(id);
            this.saveBundleInfo(id, info.setVersionName(name));
        }
    }

    private void setBundleStatus(final String id, final BundleStatus status) {
        if(id != null && status != null) {
            BundleInfo info = this.getBundleInfo(id);
            Log.d(TAG, "Setting status for [" + id + "] to " + status);
            this.saveBundleInfo(id, info.setStatus(status));
        }
    }

    private String getCurrentBundleId() {
        if(this.isUsingBuiltin()) {
            return BundleInfo.VERSION_BUILTIN;
        } else {
            final String path = this.getCurrentBundlePath();
            return path.substring(path.lastIndexOf('/') + 1);
        }
    }

    public BundleInfo getCurrentBundle() {
        return this.getBundleInfo(this.getCurrentBundleId());
    }

    public String getCurrentBundlePath() {
        return this.prefs.getString(WebView.CAP_SERVER_PATH, "public");
    }

    public Boolean isUsingBuiltin() {
        return this.getCurrentBundlePath().equals("public");
    }

    public BundleInfo getFallbackVersion() {
        final String id = this.prefs.getString(FALLBACK_VERSION, BundleInfo.VERSION_BUILTIN);
        return this.getBundleInfo(id);
    }

    private void setFallbackVersion(final BundleInfo fallback) {
        this.editor.putString(FALLBACK_VERSION,
                fallback == null
                        ? BundleInfo.VERSION_BUILTIN
                        : fallback.getVersionName()
        );
    }

    public BundleInfo getNextVersion() {
        final String id = this.prefs.getString(NEXT_VERSION, "");
        if(id != "") {
            return this.getBundleInfo(id);
        } else {
            return null;
        }
    }

    public boolean setNextVersion(final String next) {
        if (next == null) {
            this.editor.remove(NEXT_VERSION);
        } else {
            final File bundle = this.getBundleDirectory(next);
            if (!this.bundleExists(bundle)) {
                return false;
            }

            this.editor.putString(NEXT_VERSION, next);
            this.setBundleStatus(next, BundleStatus.PENDING);
        }
        this.editor.commit();
        return true;
    }

}
